In [36]:
# evaluate multinomial logistic regression model
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

In [37]:
dfTitanicTrain = pd.read_csv('train.csv')
print(dfTitanicTrain.count())
dfTitanicTrain.head()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [38]:
dfTitanicTrain.mode()

PassengerId  Survived  Pclass                                   Name  \
0              1       0.0     3.0                    Abbing, Mr. Anthony   
1              2       NaN     NaN            Abbott, Mr. Rossmore Edward   
2              3       NaN     NaN       Abbott, Mrs. Stanton (Rosa Hunt)   
3              4       NaN     NaN                    Abelson, Mr. Samuel   
4              5       NaN     NaN  Abelson, Mrs. Samuel (Hannah Wizosky)   
..           ...       ...     ...                                    ...   
886          887       NaN     NaN                de Mulder, Mr. Theodore   
887          888       NaN     NaN              de Pelsmaeker, Mr. Alfons   
888          889       NaN     NaN              del Carlo, Mr. Sebastiano   
889          890       NaN     NaN        van Billiard, Mr. Austin Blyler   
890          891       NaN     NaN            van Melkebeke, Mr. Philemon   

      Sex   Age  SibSp  Parch    Ticket  Fare        Cabin Embarked  
0    male  24.0    0.0    0.0      1601  8.05      B96 B98        S  
1     NaN   NaN    NaN    NaN    347082   NaN  C23 C25 C27      NaN  
2     NaN   NaN    NaN    NaN  CA. 2343   NaN           G6      NaN  
3     NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN  
4     NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN  
..    ...   ...    ...    ...       ...   ...          ...      ...  
886   NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN  
887   NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN  
888   NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN  
889   NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN  
890   NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN  

[891 rows x 12 columns]

In [72]:
dfTitanicTrain.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [75]:
oneHotSex = pd.get_dummies(dfTitanicTrain.Sex, prefix='Sex')
oneHotCabin = pd.get_dummies(dfTitanicTrain.Cabin, prefix='Cabin')
oneHotEmbarked = pd.get_dummies(dfTitanicTrain.Embarked, prefix='Embarked')

In [41]:
oneHotSex.head()

Sex_female  Sex_male
0           0         1
1           1         0
2           1         0
3           1         0
4           0         1

In [42]:
oneHotCabin.head()

Cabin_A10  Cabin_A14  Cabin_A16  Cabin_A19  Cabin_A20  Cabin_A23  \
0          0          0          0          0          0          0   
1          0          0          0          0          0          0   
2          0          0          0          0          0          0   
3          0          0          0          0          0          0   
4          0          0          0          0          0          0   

   Cabin_A24  Cabin_A26  Cabin_A31  Cabin_A32  ...  Cabin_E8  Cabin_F E69  \
0          0          0          0          0  ...         0            0   
1          0          0          0          0  ...         0            0   
2          0          0          0          0  ...         0            0   
3          0          0          0          0  ...         0            0   
4          0          0          0          0  ...         0            0   

   Cabin_F G63  Cabin_F G73  Cabin_F2  Cabin_F33  Cabin_F38  Cabin_F4  \
0            0            0         0          0          0         0   
1            0            0         0          0          0         0   
2            0            0         0          0          0         0   
3            0            0         0          0          0         0   
4            0            0         0          0          0         0   

   Cabin_G6  Cabin_T  
0         0        0  
1         0        0  
2         0        0  
3         0        0  
4         0        0  

[5 rows x 147 columns]

In [76]:
oneHotEmbarked.head()

Embarked_C  Embarked_Q  Embarked_S
0           0           0           1
1           1           0           0
2           0           0           1
3           0           0           1
4           0           0           1

In [81]:
dfTrain = dfTitanicTrain.join(oneHotSex)
dfTrain = dfTrain.join(oneHotCabin)
dfTrain = dfTrain.join(oneHotEmbarked)

In [51]:
dfTrain.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare  ... Cabin_E8 Cabin_F E69  Cabin_F G63  \
0      0         A/5 21171   7.2500  ...        0           0            0   
1      0          PC 17599  71.2833  ...        0           0            0   
2      0  STON/O2. 3101282   7.9250  ...        0           0            0   
3      0            113803  53.1000  ...        0           0            0   
4      0            373450   8.0500  ...        0           0            0   

   Cabin_F G73  Cabin_F2  Cabin_F33  Cabin_F38  Cabin_F4  Cabin_G6  Cabin_T  
0            0         0          0          0         0         0        0  
1            0         0          0          0         0         0        0  
2            0         0          0          0         0         0        0  
3            0         0          0          0         0         0        0  
4            0         0          0          0         0         0        0  

[5 rows x 161 columns]

In [77]:
print(dfTrain.columns)
print(oneHotSex.columns)
print(oneHotCabin.columns)
print(oneHotEmbarked.columns)


Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare',
       ...
       'Cabin_E8', 'Cabin_F E69', 'Cabin_F G63', 'Cabin_F G73', 'Cabin_F2',
       'Cabin_F33', 'Cabin_F38', 'Cabin_F4', 'Cabin_G6', 'Cabin_T'],
      dtype='object', length=161)
Index(['Sex_female', 'Sex_male'], dtype='object')
Index(['Cabin_A10', 'Cabin_A14', 'Cabin_A16', 'Cabin_A19', 'Cabin_A20',
       'Cabin_A23', 'Cabin_A24', 'Cabin_A26', 'Cabin_A31', 'Cabin_A32',
       ...
       'Cabin_E8', 'Cabin_F E69', 'Cabin_F G63', 'Cabin_F G73', 'Cabin_F2',
       'Cabin_F33', 'Cabin_F38', 'Cabin_F4', 'Cabin_G6', 'Cabin_T'],
      dtype='object', length=147)
Index(['Embarked_C', 'Embarked_Q', 'Embarked_S'], dtype='object')


In [107]:
X = dfTrain[[ 'Pclass', 'Sex_female', 'Embarked_C', 'Embarked_S', 'Embarked_S']]

y = dfTrain['Survived']

In [108]:
# test classification dataset
from collections import Counter
from sklearn.datasets import make_classification
# define dataset
#X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)
# summarize the dataset
print(X.shape, y.shape)
print(Counter(y))

(891, 5) (891,)
Counter({0: 549, 1: 342})


In [84]:
print(X)
print(y)

     PassengerId  Pclass  Sex_female   Age  Cabin_A14  Embarked_C  Embarked_S  \
0              1       3           0  22.0          0           0           1   
1              2       1           1  38.0          0           1           0   
2              3       3           1  26.0          0           0           1   
3              4       1           1  35.0          0           0           1   
4              5       3           0  35.0          0           0           1   
..           ...     ...         ...   ...        ...         ...         ...   
886          887       2           0  27.0          0           0           1   
887          888       1           1  19.0          0           0           1   
888          889       3           1   NaN          0           0           1   
889          890       1           0  26.0          0           1           0   
890          891       3           0  32.0          0           0           0   

     Embarked_S  
0        

In [109]:
# define the multinomial logistic regression model
model = LogisticRegression(multi_class='multinomial', solver='lbfgs')


In [110]:
# define the model evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate the model and collect the scores
##n_scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
# report the model performance
#print('Mean Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

In [111]:
model.fit(X,y)

LogisticRegression(multi_class='multinomial')

In [112]:
model.classes_

array([0, 1], dtype=int64)

In [113]:
model.intercept_

array([0.43650829])

In [114]:
model.coef_

array([[-0.46438839,  1.28652779,  0.06637895, -0.10189491, -0.10189491]])

In [94]:
model.predict_proba(X)

array([[0.91313473, 0.08686527],
       [0.07111197, 0.92888803],
       [0.43894368, 0.56105632],
       ...,
       [0.40475111, 0.59524889],
       [0.47186787, 0.52813213],
       [0.88500988, 0.11499012]])

In [95]:
model.predict(X)

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,

In [115]:
model.score(X, y)

0.7777777777777778

In [116]:
confusion_matrix(y, model.predict(X))

array([[443, 106],
       [ 92, 250]], dtype=int64)

In [117]:
print(classification_report(y, model.predict(X)))

              precision    recall  f1-score   support

           0       0.83      0.81      0.82       549
           1       0.70      0.73      0.72       342

    accuracy                           0.78       891
   macro avg       0.77      0.77      0.77       891
weighted avg       0.78      0.78      0.78       891



In [118]:
dfTitanicTest = pd.read_csv('test.csv')
print(dfTitanicTest.count())
dfTitanicTest.head()

PassengerId    418
Pclass         418
Name           418
Sex            418
Age            332
SibSp          418
Parch          418
Ticket         418
Fare           417
Cabin           91
Embarked       418
dtype: int64


PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [119]:
oneHotSex = pd.get_dummies(dfTitanicTest.Sex, prefix='Sex')
oneHotCabin = pd.get_dummies(dfTitanicTest.Cabin, prefix='Cabin')
oneHotEmbarked = pd.get_dummies(dfTitanicTest.Embarked, prefix='Embarked')

In [120]:
dfTest = dfTitanicTest.join(oneHotSex)
dfTest = dfTest.join(oneHotCabin)
dfTest = dfTest.join(oneHotEmbarked)

In [123]:
dfToBeScored = dfTest[['Pclass', 'Sex_female',  'Embarked_C', 'Embarked_S', 'Embarked_S']]

In [182]:
score = pd.DataFrame(model.predict(dfToBeScored), columns=['Survived'])

In [176]:
PassengerId = pd.DataFrame(dfTest['PassengerId'])

In [183]:
submission = PassengerId.join(score)

In [184]:
submission

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [185]:
submission.to_csv('submission.csv', index=False)