In [1]:
# evaluate multinomial logistic regression model
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
from loadFeatures import loadTitanic

In [3]:
train = 'train.csv'

loadTitanic(train)

In [4]:
X = pd.read_csv('Featured_train.csv', index_col='Unnamed: 0')
y = pd.read_csv('Label_train.csv', index_col='Unnamed: 0')

In [5]:
# test classification dataset
from collections import Counter
from sklearn.datasets import make_classification
# define dataset
#X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)
# summarize the dataset
print(X.shape, y.shape)
print(Counter(y))

(891, 5) (891, 1)
Counter({'Survived': 1})


In [6]:
print(X)
print(y)

     Pclass  Sex_female  CabinClass  SibSp  Parch
0         3           0       False      1      0
1         1           1        True      1      0
2         3           1       False      0      0
3         1           1        True      1      0
4         3           0       False      0      0
..      ...         ...         ...    ...    ...
886       2           0       False      0      0
887       1           1        True      0      0
888       3           1       False      1      2
889       1           0        True      0      0
890       3           0       False      0      0

[891 rows x 5 columns]
     Survived
0           0
1           1
2           1
3           1
4           0
..        ...
886         0
887         1
888         0
889         1
890         0

[891 rows x 1 columns]


In [7]:
# define the multinomial logistic regression model
model = LogisticRegression(multi_class='multinomial', solver='lbfgs')


In [8]:
# define the model evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate the model and collect the scores
##n_scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
# report the model performance
#print('Mean Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

In [9]:
model.fit(X,y)

c:\Users\rdoughty\Documents\Junk\git\KaggleComp\virEnv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(multi_class='multinomial')

In [10]:
model.score(X, y)

0.8002244668911336

In [11]:
confusion_matrix(y, model.predict(X))

array([[483,  66],
       [112, 230]], dtype=int64)

In [12]:
print(classification_report(y, model.predict(X)))

              precision    recall  f1-score   support

           0       0.81      0.88      0.84       549
           1       0.78      0.67      0.72       342

    accuracy                           0.80       891
   macro avg       0.79      0.78      0.78       891
weighted avg       0.80      0.80      0.80       891



In [13]:
X.head()

Pclass  Sex_female  CabinClass  SibSp  Parch
0       3           0       False      1      0
1       1           1        True      1      0
2       3           1       False      0      0
3       1           1        True      1      0
4       3           0       False      0      0

In [14]:
print(model.coef_)

[[-0.46777203  1.35395551 -0.0166958  -0.11452815 -0.02155463]]


In [15]:
model.classes_

array([0, 1], dtype=int64)

In [16]:
model.intercept_

array([0.35546406])

In [17]:
model.predict_proba(X)

array([[0.91090703, 0.08909297],
       [0.09789396, 0.90210604],
       [0.35155592, 0.64844408],
       ...,
       [0.42630762, 0.57369238],
       [0.56414644, 0.43585356],
       [0.89048493, 0.10951507]])

In [18]:
model.predict(X)

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,

In [26]:
test = 'test.csv'

loadTitanic(test)

Test datset. Missing Label data.


In [27]:
dfToBeScored = pd.read_csv('Featured_test.csv', index_col='Unnamed: 0')

In [28]:
score = pd.DataFrame(model.predict(dfToBeScored), columns=['Survived'])

In [29]:
PassengerId = pd.DataFrame(pd.read_csv('test.csv')['PassengerId'])

In [30]:
submission = PassengerId.join(score)

In [31]:
submission

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [32]:
submission.to_csv('submission.csv', index=False)