In [36]:
# evaluate multinomial logistic regression model
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

In [37]:
dfTitanicTrain = pd.read_csv('train.csv')
print(dfTitanicTrain.count())
dfTitanicTrain.head()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [38]:
dfTitanicTrain.mode()

PassengerId  Survived  Pclass                                   Name  \
0              1       0.0     3.0                    Abbing, Mr. Anthony   
1              2       NaN     NaN            Abbott, Mr. Rossmore Edward   
2              3       NaN     NaN       Abbott, Mrs. Stanton (Rosa Hunt)   
3              4       NaN     NaN                    Abelson, Mr. Samuel   
4              5       NaN     NaN  Abelson, Mrs. Samuel (Hannah Wizosky)   
..           ...       ...     ...                                    ...   
886          887       NaN     NaN                de Mulder, Mr. Theodore   
887          888       NaN     NaN              de Pelsmaeker, Mr. Alfons   
888          889       NaN     NaN              del Carlo, Mr. Sebastiano   
889          890       NaN     NaN        van Billiard, Mr. Austin Blyler   
890          891       NaN     NaN            van Melkebeke, Mr. Philemon   

      Sex   Age  SibSp  Parch    Ticket  Fare        Cabin Embarked  
0    male  24.0    0.0    0.0      1601  8.05      B96 B98        S  
1     NaN   NaN    NaN    NaN    347082   NaN  C23 C25 C27      NaN  
2     NaN   NaN    NaN    NaN  CA. 2343   NaN           G6      NaN  
3     NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN  
4     NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN  
..    ...   ...    ...    ...       ...   ...          ...      ...  
886   NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN  
887   NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN  
888   NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN  
889   NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN  
890   NaN   NaN    NaN    NaN       NaN   NaN          NaN      NaN  

[891 rows x 12 columns]

In [72]:
dfTitanicTrain.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [39]:
dfTitanicTrain.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [40]:
oneHotSex = pd.get_dummies(dfTitanicTrain.Sex, prefix='Sex')
oneHotCabin = pd.get_dummies(dfTitanicTrain.Cabin, prefix='Cabin')

In [41]:
oneHotSex.head()

Sex_female  Sex_male
0           0         1
1           1         0
2           1         0
3           1         0
4           0         1

In [42]:
oneHotCabin.head()

Cabin_A10  Cabin_A14  Cabin_A16  Cabin_A19  Cabin_A20  Cabin_A23  \
0          0          0          0          0          0          0   
1          0          0          0          0          0          0   
2          0          0          0          0          0          0   
3          0          0          0          0          0          0   
4          0          0          0          0          0          0   

   Cabin_A24  Cabin_A26  Cabin_A31  Cabin_A32  ...  Cabin_E8  Cabin_F E69  \
0          0          0          0          0  ...         0            0   
1          0          0          0          0  ...         0            0   
2          0          0          0          0  ...         0            0   
3          0          0          0          0  ...         0            0   
4          0          0          0          0  ...         0            0   

   Cabin_F G63  Cabin_F G73  Cabin_F2  Cabin_F33  Cabin_F38  Cabin_F4  \
0            0            0         0          0          0         0   
1            0            0         0          0          0         0   
2            0            0         0          0          0         0   
3            0            0         0          0          0         0   
4            0            0         0          0          0         0   

   Cabin_G6  Cabin_T  
0         0        0  
1         0        0  
2         0        0  
3         0        0  
4         0        0  

[5 rows x 147 columns]

In [43]:
dfTrain = dfTitanicTrain.join(oneHotSex)
dfTrain = dfTrain.join(oneHotCabin)

In [51]:
dfTrain.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare  ... Cabin_E8 Cabin_F E69  Cabin_F G63  \
0      0         A/5 21171   7.2500  ...        0           0            0   
1      0          PC 17599  71.2833  ...        0           0            0   
2      0  STON/O2. 3101282   7.9250  ...        0           0            0   
3      0            113803  53.1000  ...        0           0            0   
4      0            373450   8.0500  ...        0           0            0   

   Cabin_F G73  Cabin_F2  Cabin_F33  Cabin_F38  Cabin_F4  Cabin_G6  Cabin_T  
0            0         0          0          0         0         0        0  
1            0         0          0          0         0         0        0  
2            0         0          0          0         0         0        0  
3            0         0          0          0         0         0        0  
4            0         0          0          0         0         0        0  

[5 rows x 161 columns]

In [45]:
X = dfTitanicTrain[['PassengerId', 'Pclass', 'Sex_female', 'Age', 'Cabin', 'Embarked']]

y = dfTitanicTrain['Survived']

In [46]:
# test classification dataset
from collections import Counter
from sklearn.datasets import make_classification
# define dataset
#X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)
# summarize the dataset
print(X.shape, y.shape)
print(Counter(y))

(891, 11) (891,)
Counter({0: 549, 1: 342})


In [47]:
print(X)
print(y)

     PassengerId  Pclass                                               Name  \
0              1       3                            Braund, Mr. Owen Harris   
1              2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2              3       3                             Heikkinen, Miss. Laina   
3              4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4              5       3                           Allen, Mr. William Henry   
..           ...     ...                                                ...   
886          887       2                              Montvila, Rev. Juozas   
887          888       1                       Graham, Miss. Margaret Edith   
888          889       3           Johnston, Miss. Catherine Helen "Carrie"   
889          890       1                              Behr, Mr. Karl Howell   
890          891       3                                Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket  

In [48]:
# define the multinomial logistic regression model
model = LogisticRegression(multi_class='multinomial', solver='lbfgs')


In [49]:
# define the model evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate the model and collect the scores
##n_scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
# report the model performance
#print('Mean Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

In [50]:
model.fit(X,y)

ValueError: could not convert string to float: 'Braund, Mr. Owen Harris'

In [ ]:
model.classes_

array([0, 1])

In [ ]:
model.intercept_

array([-0.31881216])

In [ ]:
model.coef_

array([[ 0.08170741, -0.3227106 ,  0.24332307, -0.23144234,  0.0924704 ,
        -0.05980723, -0.20377054,  0.01903862, -0.26012959,  0.13310918]])

In [ ]:
model.predict_proba(X)

array([[0.04382755, 0.95617245],
       [0.73337381, 0.26662619],
       [0.82013696, 0.17986304],
       ...,
       [0.81563862, 0.18436138],
       [0.64566253, 0.35433747],
       [0.39799477, 0.60200523]])

In [ ]:
model.predict(X)

array([1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,

In [ ]:
model.score(X, y)

0.806

In [ ]:
confusion_matrix(y, model.predict(X))

array([[424,  75],
       [119, 382]], dtype=int64)

In [ ]:
print(classification_report(y, model.predict(X)))

              precision    recall  f1-score   support

           0       0.78      0.85      0.81       499
           1       0.84      0.76      0.80       501

    accuracy                           0.81      1000
   macro avg       0.81      0.81      0.81      1000
weighted avg       0.81      0.81      0.81      1000

